module.exports = Object.freeze({

    API_ACP_CONTENT_TYPE: 'API_ACP_CONTENT_TYPE',
    API_ACP_OAUTH_GRANT_TYPE: 'API_ACP_OAUTH_GRANT_TYPE',
    API_ACP_OAUTH_CLIENT_ID: 'API_ACP_OAUTH_CLIENT_ID',
    API_ACP_OAUTH_CLIENT_SECRET: 'API_ACP_OAUTH_CLIENT_SECRET',
    API_ACP_OAUTH_REFRESH_TOKEN: 'API_ACP_OAUTH_REFRESH_TOKEN',
    API_ACP_OAUTH_CONTENT_TYPE: 'API_ACP_OAUTH_CONTENT_TYPE',
    API_ACP_OAUTH_URL: 'API_ACP_OAUTH_URL',
    API_ACP_URL_APIXML: 'API_ACP_URL_APIXML',
    SFTP_HOST: 'SFTP_HOST',
    SFTP_PORT: 'SFTP_PORT',
    SFTP_USERNAME: 'SFTP_USERNAME',
    SFTP_PASSWORD: 'SFTP_PASSWORD',
    API_ACP_XMLAPI_BULKIMPORT_BODY: 'API_ACP_XMLAPI_BULKIMPORT_BODY',
    HTTP_OK: 200,
    FIELD_FILE_NAME: '{{fileName}}',

    ACP_ESTATUSJOB_RETRY_SLEEP: 'ACP_ESTATUSJOB_RETRY_SLEEP',
    SERVICEBUS_CONNECTION: 'SERVICEBUS_CONNECTION',
    API_ACP_CONTENT_TABLE_IMPORT: 'API_ACP_CONTENT_TABLE_IMPORT',
    ACP_CRON: "ACP_CRON",
    

    
    TOPIC_SEND_BULK_EMAILS_SEND_MAIL_TEMPLATE_ID: 'TOPIC_SEND_BULK_EMAILS_SEND_MAIL_TEMPLATE_ID',
    TOPIC_SEND_BULK_EMAILS_SEND_MAIL_LIST_ID: 'TOPIC_SEND_BULK_EMAILS_SEND_MAIL_LIST_ID',
    TOPIC_SEND_BULK_EMAILS_SEND_MAIL_MAILING_NAME: 'TOPIC_SEND_BULK_EMAILS_SEND_MAIL_MAILING_NAME',
    TOPIC_SEND_BULK_EMAILS_SEND_MAIL_SUBJECT: 'TOPIC_SEND_BULK_EMAILS_SEND_MAIL_SUBJECT',
    TOPIC_SEND_BULK_EMAILS_SEND_MAIL_FROM_NAME: 'TOPIC_SEND_BULK_EMAILS_SEND_MAIL_FROM_NAME',
    TOPIC_SEND_BULK_EMAILS_SEND_MAIL_FROM_ADDRESS: 'TOPIC_SEND_BULK_EMAILS_SEND_MAIL_FROM_ADDRESS',
    TOPIC_SEND_BULK_EMAILS_SEND_MAIL_REPLY_TO: 'TOPIC_SEND_BULK_EMAILS_SEND_MAIL_REPLY_TO',
    TOPIC_SEND_BULK_EMAILS_SEND_MAIL_VISIBILITY: 'TOPIC_SEND_BULK_EMAILS_SEND_MAIL_VISIBILITY',
    APPLICATIONINSIGHTKEY:"APPLICATIONINSIGHTKEY",
    ACP_URL_SLACK:"ACP_URL_SLACK",
    ACP_KEY_AUTH_CODE: "ACP_KEY_AUTH_CODE",
    TOPIC_RETRY_NAME:"TOPIC_RETRY_NAME",
    TOPIC_RETRY_LABEL:"TOPIC_RETRY_LABEL",
    TOPIC_RETRY_NAME_SUSCRIPTION:"TOPIC_RETRY_NAME_SUSCRIPTION",
    RETRY_MAX_COUNT:"RETRY_MAX_COUNT",
    URL_IMG_CH:"URL_IMG_CH",

    TOPIC_SEND_EMAIL_IMPORTRECORD_NAME:"TOPIC_SEND_EMAIL_IMPORTRECORD_NAME",
    TOPIC_SEND_EMAIL_IMPORTRECORD_LABEL:"TOPIC_SEND_EMAIL_IMPORTRECORD_LABEL",
    TOPIC_SEND_EMAIL_IMPORTRECORD_SUSCRIPTION:"TOPIC_SEND_EMAIL_IMPORTRECORD_SUSCRIPTION",

    TOPIC_SEND_EMAIL_JOBSTATUS_NAME:"TOPIC_SEND_EMAIL_JOBSTATUS_NAME",
    TOPIC_SEND_EMAIL_JOBSTATUS_LABEL:"TOPIC_SEND_EMAIL_JOBSTATUS_LABEL",
    TOPIC_SEND_EMAIL_JOBSTATUS_SUSCRIPTION:"TOPIC_SEND_EMAIL_JOBSTATUS_SUSCRIPTION",

    TOPIC_SEND_EMAIL_SENDMAIL_NAME:"TOPIC_SEND_EMAIL_SENDMAIL_NAME",
    TOPIC_SEND_EMAIL_SENDMAIL_LABEL:"TOPIC_SEND_EMAIL_SENDMAIL_LABEL",
    TOPIC_SEND_EMAIL_SENDMAIL_SUSCRIPTION:"TOPIC_SEND_EMAIL_SENDMAIL_SUSCRIPTION",


    TOPIC_SEND_EMAIL_RETRY_NAME:"TOPIC_SEND_EMAIL_RETRY_NAME",
    TOPIC_SEND_EMAIL_RETRY_LABEL:"TOPIC_SEND_EMAIL_RETRY_LABEL",
    TOPIC_SEND_EMAIL_RETRY_SUSCRIPTION:"TOPIC_SEND_EMAIL_RETRY_SUSCRIPTION",

    COD_DOC:"COD_DOC",
    TIP_DOC:"TIP_DOC",
    EMAIL:"cocaresh@intercorp.com.pe",

    

});